name: CI
on: [push]
jobs:
  eslint:
    name: Github Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn

      - name: Print Node Version
        run: node -v
