name: CI
on: [push]
jobs:
  eslint:
    name: Github Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn

      - name: Lint Code
        run: yarn ci:lint

      - name: Test Code with JEST
        run: yarn ci:test
